"""`pprose install` and `pprose skill` — install the Practical Prose skills.

`install` writes generated SKILL.md files into a target repo's `.claude/skills/`,
each carrying a pinned, local-first invocation block so the skill runs the exact
pprose version that installed it (supply-chain hardening) and still works in any
repo, with or without pprose installed.
"""

from __future__ import annotations

import argparse
from importlib.metadata import PackageNotFoundError, version
from pathlib import Path

from pprose import resources

PACKAGE_NAME = "pprose"
DO_NOT_EDIT = "<!-- DO NOT EDIT: generated by `pprose install`. Re-run it to regenerate. -->"

_INVOCATION = """\
## Running pprose

Run pprose with the first available option:

1. `pprose <command>` — if `pprose` is on the PATH (local dev, or
   `uv tool install pprose`).
2. `uvx pprose@{version} <command>` — zero-install via uv, pinned to a trusted version.

If neither `pprose` nor `uvx` is available, stop and tell the user: "pprose needs `uvx`
(from Astral's uv) or `pprose` on the PATH — install uv (https://docs.astral.sh/uv/) or
run `uv tool install pprose`."
"""

BEGIN_MARKER = "<!-- BEGIN PPROSE -->"
END_MARKER = "<!-- END PPROSE -->"


def pinned_version() -> str:
    """The running pprose version, used as the pin in generated skills.

    A local/dev build looks like `0.0.1.dev49+<sha>`; that won't resolve via
    `uvx` until published, but the local-first rule means the uvx fallback is
    only used once a real version is installed.
    """
    try:
        return version(PACKAGE_NAME)
    except PackageNotFoundError:
        return "0.0.0"


def render_invocation(pin: str) -> str:
    return _INVOCATION.format(version=pin)


def _split_frontmatter(raw: str) -> tuple[str, str]:
    """Return (frontmatter_without_delimiters, body). Empty frontmatter if absent."""
    lines = raw.splitlines()
    if lines and lines[0].strip() == "---":
        for i in range(1, len(lines)):
            if lines[i].strip() == "---":
                return "\n".join(lines[1:i]), "\n".join(lines[i + 1 :]).lstrip("\n")
    return "", raw


def compose_skill(name: str, pin: str) -> str:
    """Build the installed SKILL.md: frontmatter + DO-NOT-EDIT + invocation + body."""
    fm, body = _split_frontmatter(resources.read_doc("skills", name))
    head = f"---\n{fm}\n---\n" if fm else ""
    return f"{head}{DO_NOT_EDIT}\n\n{render_invocation(pin)}\n{body}".rstrip() + "\n"


def _skill_description(name: str) -> str:
    fm, _ = _split_frontmatter(resources.read_doc("skills", name))
    for line in fm.splitlines():
        if line.startswith("description:"):
            return line.split(":", 1)[1].strip()
    return ""


def skill_main(argv: list[str] | None = None) -> int:
    parser = argparse.ArgumentParser(description="Print a composed Practical Prose skill.")
    parser.add_argument("name", nargs="?", help="skill name (omit with --list)")
    parser.add_argument("--list", action="store_true", help="list installable skills")
    args = parser.parse_args(argv)

    if args.list or not args.name:
        for name in resources.list_names("skills"):
            print(f"{name}\t{_skill_description(name)}")
        return 0
    try:
        print(compose_skill(args.name, pinned_version()))
    except FileNotFoundError as exc:
        parser.error(str(exc))
    return 0


def _update_marked_section(existing: str, section: str) -> str:
    """Replace the BEGIN/END pprose block in `existing`, or append it."""
    start = existing.find(BEGIN_MARKER)
    end = existing.find(END_MARKER)
    if start != -1 and end != -1:
        return existing[:start] + section + existing[end + len(END_MARKER) :]
    sep = "" if existing.endswith("\n\n") or not existing else "\n"
    return f"{existing}{sep}\n{section}\n"


def _agents_md_section(pin: str, skills: list[str]) -> str:
    lines = [
        BEGIN_MARKER,
        "## Practical Prose (pprose)",
        "",
        f"Run pprose as `pprose <command>` if on PATH, else `uvx pprose@{pin} <command>`.",
        "Installed skills:",
        "",
    ]
    lines += [f"- `{s}`" for s in skills]
    lines.append(END_MARKER)
    return "\n".join(lines)


def install_main(argv: list[str] | None = None) -> int:
    parser = argparse.ArgumentParser(
        description="Install the Practical Prose skills into a repo's .claude/skills/."
    )
    parser.add_argument("--dir", default=".", help="target repo root (default: cwd)")
    parser.add_argument("--auto", action="store_true", help="non-interactive (for agents)")
    parser.add_argument("--print", action="store_true", help="print to stdout, write nothing")
    parser.add_argument("--agents-md", action="store_true", help="also update AGENTS.md")
    args = parser.parse_args(argv)

    pin = pinned_version()
    skills = resources.list_names("skills")
    target = Path(args.dir).resolve()

    if args.print:
        for name in skills:
            print(f"# === .claude/skills/{name}/SKILL.md ===")
            print(compose_skill(name, pin))
        return 0

    skills_root = target / ".claude" / "skills"
    for name in skills:
        dest = skills_root / name / "SKILL.md"
        dest.parent.mkdir(parents=True, exist_ok=True)
        dest.write_text(compose_skill(name, pin), encoding="utf-8")
    print(f"installed {len(skills)} skills into {skills_root} (pinned pprose@{pin})")

    if args.agents_md:
        agents = target / "AGENTS.md"
        existing = agents.read_text(encoding="utf-8") if agents.is_file() else ""
        agents.write_text(
            _update_marked_section(existing, _agents_md_section(pin, skills)), encoding="utf-8"
        )
        print(f"updated {agents}")

    print(f"skills: {', '.join(skills)}")
    return 0
