"""`pprose install` and `pprose skill` — install Practical Prose skills into a repo.

`pprose install` runs in one of two **scopes**:

- **Project** (`--project`, the default when cwd is unambiguously inside a git repo)
  writes into `<target>/.agents/skills/<name>/SKILL.md` (Codex/Gemini CLI/pi),
  `<target>/.claude/skills/<name>/SKILL.md` (Claude Code), and a marker-bounded
  block in `<target>/AGENTS.md`.
- **User-global** (`--global`) writes into `$HOME/.agents/skills/<name>/SKILL.md`
  and `$HOME/.claude/skills/<name>/SKILL.md`, making the skills available across
  every project. Global mode never writes `$HOME/.codex/AGENTS.md` (skills are
  on-demand; the global AGENTS.md should stay compact and user-authored).

Outside an unambiguous project context (e.g. `$HOME`, `/tmp/scratch`, or any other
directory not inside a git repo), `--project` or `--global` must be passed explicitly
— there's no silent default.

The `--surfaces=portable,claude,agents-md` flag selects install destinations within
the chosen scope. `portable` → `.agents/skills/`; `claude` → `.claude/skills/`;
`agents-md` → marker block in `AGENTS.md` (project mode only).

Every generated artifact carries a `format=fNN` stamp so future pprose versions can
detect and refresh older layouts, and refuse to clobber any artifact stamped with a
newer format than they understand. The artifact type is identified by its location
(a `SKILL.md` under `.agents/skills/<name>/` or `.claude/skills/<name>/`, or the
BEGIN/END-bounded block inside `AGENTS.md`) rather than by an in-file tag, so the
portable and Claude `SKILL.md` copies stay byte-identical.
"""

from __future__ import annotations

import argparse
import re
import sys
from importlib.metadata import PackageNotFoundError, version
from pathlib import Path
from typing import NamedTuple

from flowmark import reformat_text

from pprose import resources

PACKAGE_NAME = "pprose"

# Single monotonically-increasing format version stamped onto every pprose-generated
# artifact. Bump when the on-disk shape changes so a future pprose can upgrade older
# layouts and a forward-compat guard can refuse to clobber a newer format.
PPROSE_FORMAT = "f01"

# Pinned skill bootstrap fallback when an editable/dev pprose is installed. A dev build
# reports a PEP 440 dev/local segment that was never published to PyPI, so
# `uvx pprose@<dev-pin>` won't resolve. Bump on each real PyPI release and re-render
# the committed discovery copies under `skills/` at the repo root (`make generate`).
# Enforced at release time: `devtools/check_release_version.py` (run from publish.yml)
# fails the publish unless this equals the release tag.
DISCOVERY_VERSION = "0.2.0"

# Install scopes.
SCOPE_PROJECT = "project"
SCOPE_GLOBAL = "global"

# Install-selector surfaces (the `--surfaces=` flag values + InstallResult.surface).
# These are install *destinations*, not artifact identities.
SURFACE_PORTABLE = "portable"  # .agents/skills/<name>/SKILL.md
SURFACE_CLAUDE = "claude"  # .claude/skills/<name>/SKILL.md
SURFACE_AGENTS_MD = "agents-md"  # marker block in AGENTS.md (project mode only)
ALL_INSTALL_SURFACES = frozenset({SURFACE_PORTABLE, SURFACE_CLAUDE, SURFACE_AGENTS_MD})
_VALID_SURFACE_TOKENS = sorted(ALL_INSTALL_SURFACES | {"all"})

PORTABLE_SKILLS_DIR = Path(".agents") / "skills"
CLAUDE_SKILLS_DIR = Path(".claude") / "skills"

AGENTS_BEGIN_PREFIX = "<!-- BEGIN PPROSE INTEGRATION"
AGENTS_END_MARKER = "<!-- END PPROSE INTEGRATION -->"
_AGENTS_BLOCK_RE = re.compile(
    re.escape(AGENTS_BEGIN_PREFIX) + r".*?" + re.escape(AGENTS_END_MARKER), re.DOTALL
)
# Anchored on the BEGIN prefix so a stray `format=fXX` elsewhere can't fool the guard.
_AGENTS_BEGIN_STAMP_RE = re.compile(re.escape(AGENTS_BEGIN_PREFIX) + r"\s+format=f(\d+)")

# Format-stamp inside a generated SKILL.md (DO NOT EDIT marker line). Anchored on
# `pprose install` so it doesn't match a stray `format=fNN` from another tool.
_SKILL_STAMP_RE = re.compile(r"generated by `pprose install`.*?format=f(\d+)")

# PEP 440 release identifier: digits + dots, optional `.postN`. Dev (`.devN`), pre-
# release (`aN`/`bN`/`rcN`/`cN`), and local (`+<hash>`) versions are rejected — they
# were never uploaded to PyPI, so `uvx pprose@<dev-pin>` against them can't resolve.
_PYPI_RELEASE_RE = re.compile(r"^\d+(?:\.\d+)*(?:\.post\d+)?$")


# ─────────────────────────────────────────────────────────────────────────────
# Version pin handling
# ─────────────────────────────────────────────────────────────────────────────


def is_pypi_release(version_str: str) -> bool:
    """Whether `version_str` is a real, exact-pinnable published PyPI release."""
    return bool(_PYPI_RELEASE_RE.match(version_str))


def pinned_version() -> str:
    """Version to bake into the `uvx pprose@<pin>` fallback in generated skills.

    Returns the installed pprose version when it is a real PyPI release, otherwise
    `DISCOVERY_VERSION`. Editable/dev checkouts report a PEP 440 dev/local version
    that uvx can't resolve, so we pin to the last published release in that case.
    """
    try:
        installed = version(PACKAGE_NAME)
    except PackageNotFoundError:
        return DISCOVERY_VERSION
    return installed if is_pypi_release(installed) else DISCOVERY_VERSION


def _format_num() -> int:
    return int(PPROSE_FORMAT.lstrip("f"))


# ─────────────────────────────────────────────────────────────────────────────
# Scope resolution and pre-flight guards
# ─────────────────────────────────────────────────────────────────────────────


def _is_within_git_repo(path: Path) -> bool:
    """Whether `path` or any ancestor contains a `.git` entry.

    `.git` is a directory in a regular repo and a file in a worktree/submodule, so
    `.exists()` covers both.
    """
    for p in (path, *path.parents):
        if (p / ".git").exists():
            return True
    return False


def _protected_target_reason(path: Path) -> str | None:
    """Return a human-readable reason if `path` is a path project-mode refuses to write to.

    `$HOME` and the filesystem root are the cases where a project-local install would
    silently land on the user's *global* agent surfaces (`~/.claude/skills/`,
    `~/.agents/skills/`, `~/AGENTS.md`). Anywhere else outside a git repo is caught
    by the git-repo guard.
    """
    resolved = path.resolve()
    if resolved.parent == resolved:
        return "filesystem root"
    try:
        if resolved == Path.home().resolve():
            return "home directory ($HOME)"
    except (OSError, RuntimeError):
        # Path.home() can raise on misconfigured systems; better safe than sorry.
        pass
    return None


# ─────────────────────────────────────────────────────────────────────────────
# Surface parsing
# ─────────────────────────────────────────────────────────────────────────────


class SurfaceSpec(NamedTuple):
    """Parsed `--surfaces` value plus a flag for whether `agents-md` was named explicitly.

    Tracking explicit `agents-md` lets `install_main` distinguish "user passed
    `--surfaces=all` (silently drop agents-md in global mode)" from "user passed
    `--surfaces=agents-md` (error in global mode)".
    """

    surfaces: frozenset[str]
    agents_md_explicit: bool


def parse_surfaces(raw: str | None) -> SurfaceSpec:
    """Parse a `--surfaces=<comma-list>` value.

    `None` or omitted → all install surfaces.
    Tokens: any subset of `{portable, claude, agents-md}` plus the `all` alias.
    Empty or unknown tokens raise `ValueError` with a clear valid-values message.
    """
    if raw is None:
        return SurfaceSpec(ALL_INSTALL_SURFACES, agents_md_explicit=False)
    tokens = [t.strip() for t in raw.split(",") if t.strip()]
    if not tokens:
        raise ValueError(
            "--surfaces is empty; pass a comma-separated list of: "
            + ", ".join(_VALID_SURFACE_TOKENS)
        )
    expanded: set[str] = set()
    agents_md_explicit = False
    for tok in tokens:
        if tok == "all":
            expanded |= ALL_INSTALL_SURFACES
        elif tok in ALL_INSTALL_SURFACES:
            expanded.add(tok)
            if tok == SURFACE_AGENTS_MD:
                agents_md_explicit = True
        else:
            raise ValueError(f"unknown surface {tok!r}; valid: " + ", ".join(_VALID_SURFACE_TOKENS))
    return SurfaceSpec(frozenset(expanded), agents_md_explicit)


# ─────────────────────────────────────────────────────────────────────────────
# Skill content composition
# ─────────────────────────────────────────────────────────────────────────────


def _flowmark(text: str) -> str:
    """Format generated Markdown exactly as the repo's flowmark pre-commit hook would.

    pprose *generates* Markdown (the composed `SKILL.md` files and the `AGENTS.md`
    block); the repo's pre-commit hook then runs `flowmark-rs --auto` over those same
    files. Pre-applying the byte-identical flowmark-py transform here makes generation
    idempotent: `make generate`, `pprose install`, and the `test_resources_sync` drift
    check all emit flowmark-clean output the hook leaves untouched — instead of long
    lines the hook silently rewraps into uncommitted drift (the original CI break).

    The flags mirror flowmark-rs `--auto` and are verified byte-identical against it
    (see tests/test_install.py::test_generated_skills_are_flowmark_stable). flowmark is
    a guaranteed dependency (direct, and transitively via flexdoc), so this never
    falls back to unformatted output.
    """
    return reformat_text(text, width=88, semantic=True, cleanups=True, smartquotes=True)


def _split_frontmatter(raw: str) -> tuple[str, str]:
    """Return (frontmatter_without_delimiters, body). Empty frontmatter if absent."""
    lines = raw.splitlines()
    if lines and lines[0].strip() == "---":
        for i in range(1, len(lines)):
            if lines[i].strip() == "---":
                return "\n".join(lines[1:i]), "\n".join(lines[i + 1 :]).lstrip("\n")
    return "", raw


def _skill_marker() -> str:
    # No internal `.` in the marker text so a flowmark/sentence-wrap pass leaves the
    # line intact. The artifact type is identified by file location (SKILL.md under a
    # `.agents/skills/<name>/` or `.claude/skills/<name>/` directory); the only
    # load-bearing field here is the format stamp.
    return f"<!-- DO NOT EDIT: generated by `pprose install` (format={PPROSE_FORMAT}) -->"


def _bootstrap_line(pin: str) -> str:
    return (
        f"> Run pprose as `pprose <command>` if on PATH, else `uvx pprose@{pin} <command>` "
        f"(zero-install via uv). Run `pprose --help` for every command, `pprose skill` "
        f"for the other Practical Prose skills, and `pprose list` for all on-demand "
        f"playbooks, style guides, and procedures (`pprose shortcut`, `pprose guidelines`, "
        f"`pprose runbook` each print one by name)."
    )


def compose_skill(name: str, pin: str | None = None) -> str:
    """Render an installable SKILL.md: frontmatter + DO-NOT-EDIT marker + bootstrap + body.

    Deterministic: same inputs produce byte-identical output (no timestamps, no machine
    paths), so the drift test for committed discovery copies under `skills/` is stable
    across machines and CI.
    """
    pin = pin if pin is not None else pinned_version()
    fm, body = _split_frontmatter(resources.read_doc("skills", name))
    head = f"---\n{fm}\n---\n" if fm else ""
    composed = f"{head}{_skill_marker()}\n\n{_bootstrap_line(pin)}\n\n{body}"
    return _flowmark(composed).rstrip() + "\n"


def _skill_description(name: str) -> str:
    fm, _ = _split_frontmatter(resources.read_doc("skills", name))
    for line in fm.splitlines():
        if line.startswith("description:"):
            return line.split(":", 1)[1].strip()
    return ""


def _print_skill_table() -> None:
    for name in resources.list_names("skills"):
        print(f"{name}\t{_skill_description(name)}")


def _print_skill_overview() -> None:
    """Intro paragraph + skill table + routing footer.

    The natural entry-point answer to "what does pprose do?" — `pprose skill` (no
    args) is short enough to skim and points the agent at the full bundled
    inventory (`pprose list`) for everything else.
    """
    print(
        "Practical Prose skills are workflow entry points for improving, auditing,\n"
        "scoring, or comparing practical documents. Each names a clear capability;\n"
        "run `pprose skill <name>` for the full composed SKILL.md.\n"
    )
    _print_skill_table()
    print(
        "\nFor deeper detail, the skills route to:\n"
        "  pprose list      — every bundled guideline, shortcut, runbook, and skill\n"
        "  pprose guidelines <name>   — a bundled style guide or writing rules\n"
        "  pprose shortcut <name>     — a workflow playbook the skills invoke\n"
        "  pprose runbook <name>      — an operational procedure (eval, compare)\n"
        "  pprose about               — the Practical Prose project narrative\n"
    )


def skill_main(argv: list[str] | None = None) -> int:
    parser = argparse.ArgumentParser(
        description=(
            "Print a Practical Prose skill: `pprose skill <name>` for the full composed "
            "SKILL.md, or `pprose skill` with no name for an overview of all skills."
        )
    )
    parser.add_argument("name", nargs="?", help="skill name; omit for an overview")
    args = parser.parse_args(argv)

    if args.name:
        try:
            print(compose_skill(args.name))
        except FileNotFoundError as exc:
            parser.error(str(exc))
        return 0
    _print_skill_overview()
    return 0


def agents_md_block(pin: str | None = None) -> str:
    """The marker-bounded pprose block for a project's `AGENTS.md`.

    Minimal by design (it sits in the always-on AGENTS.md context alongside other
    tools' blocks and any hand-authored project content). Carries only the trigger
    description plus pointers at `pprose --help` and the CLI list commands; the
    per-skill bullet list is gone (run `pprose skill` for that). The `format=fNN`
    field on the BEGIN marker lets a future pprose detect and upgrade older blocks
    (and refuse to clobber a newer one).
    """
    pin = pin if pin is not None else pinned_version()
    # Authored as long lines; _flowmark applies the same semantic wrapping the
    # pre-commit hook would, so the block stays idempotent inside AGENTS.md.
    block = "\n".join(
        [
            f"{AGENTS_BEGIN_PREFIX} format={PPROSE_FORMAT} -->",
            "## Practical Prose (pprose)",
            "",
            "Practical Prose: an evaluation toolkit and editorial workflows for practical "
            "documents. Use when the user asks to improve, audit, score, or compare "
            "practical documents.",
            "",
            "Discover the tool from the CLI itself: `pprose --help` for commands, "
            "`pprose about` for the project narrative, `pprose skill` for the workflow "
            "skills, and `pprose list` for every on-demand guideline, shortcut, and "
            "runbook (`pprose guidelines|shortcut|runbook <name>` prints one).",
            "",
            f"Run pprose as `pprose <command>` if on PATH, else `uvx pprose@{pin} "
            "<command>` (zero-install via uv).",
            "",
            AGENTS_END_MARKER,
        ]
    )
    return _flowmark(block).rstrip()


# ─────────────────────────────────────────────────────────────────────────────
# Filesystem writes
# ─────────────────────────────────────────────────────────────────────────────


class InstallResult(NamedTuple):
    """Per-artifact result from a `pprose install` run."""

    surface: str  # SURFACE_PORTABLE, SURFACE_CLAUDE, or SURFACE_AGENTS_MD
    skill: str | None  # skill name for a SKILL.md write, else None
    path: Path
    action: str  # "installed" | "updated" | "unchanged" | "blocked-newer"


def _existing_skill_format(path: Path) -> int | None:
    """Format number stamped on an existing generated SKILL.md; 0 if unmarked; None if absent."""
    if not path.is_file():
        return None
    m = _SKILL_STAMP_RE.search(path.read_text(encoding="utf-8"))
    return int(m.group(1)) if m else 0


def _write_atomic(path: Path, content: str) -> None:
    path.parent.mkdir(parents=True, exist_ok=True)
    tmp = path.with_suffix(path.suffix + ".tmp")
    tmp.write_text(content, encoding="utf-8")
    tmp.replace(path)


def _write_skill_file(skill_dir: Path, surface: str, name: str, content: str) -> InstallResult:
    out = skill_dir / "SKILL.md"
    existing = _existing_skill_format(out)
    # Forward-compatibility guard: never clobber a newer-format artifact.
    if existing is not None and existing > _format_num():
        return InstallResult(surface, name, out, "blocked-newer")
    if out.is_file() and out.read_text(encoding="utf-8") == content:
        return InstallResult(surface, name, out, "unchanged")
    action = "updated" if out.exists() else "installed"
    _write_atomic(out, content)
    return InstallResult(surface, name, out, action)


def _update_agents_md(path: Path, block: str) -> InstallResult:
    """Insert or refresh the pprose block in `AGENTS.md`, preserving content outside markers.

    Collapses duplicate or stale blocks to one current block at the position of the
    first stale block.
    """
    existing = path.read_text(encoding="utf-8") if path.is_file() else None

    if existing is not None and (m := _AGENTS_BEGIN_STAMP_RE.search(existing)):
        if int(m.group(1)) > _format_num():
            return InstallResult(SURFACE_AGENTS_MD, None, path, "blocked-newer")

    if existing is None or AGENTS_BEGIN_PREFIX not in existing:
        if not existing:
            new_content = block + "\n"
        else:
            sep = "\n" if existing.endswith("\n") else "\n\n"
            new_content = existing + sep + block + "\n"
    else:
        # Replace every existing block (collapses stale duplicates to one).
        matches = list(_AGENTS_BLOCK_RE.finditer(existing))
        head = existing[: matches[0].start()]
        tail_parts = [
            existing[matches[i - 1].end() : matches[i].start()] for i in range(1, len(matches))
        ]
        tail_parts.append(existing[matches[-1].end() :])
        new_content = head + block + "".join(tail_parts)

    if existing == new_content:
        return InstallResult(SURFACE_AGENTS_MD, None, path, "unchanged")
    action = "updated" if existing is not None else "installed"
    _write_atomic(path, new_content)
    return InstallResult(SURFACE_AGENTS_MD, None, path, action)


def install(
    target_root: Path,
    surfaces: frozenset[str] = ALL_INSTALL_SURFACES,
    *,
    pin: str | None = None,
) -> list[InstallResult]:
    """Install pprose skills into `target_root`, returning per-artifact results.

    `surfaces` is any subset of {`SURFACE_PORTABLE`, `SURFACE_CLAUDE`,
    `SURFACE_AGENTS_MD`}. The caller is responsible for scope-specific filtering
    (e.g. user-global mode should drop `SURFACE_AGENTS_MD` before calling).

    `pin` overrides the version pin baked into generated skills (defaults to the
    running pprose version when it's a real PyPI release, else `DISCOVERY_VERSION`).

    Idempotent: re-running an up-to-date install reports `unchanged` and writes nothing.
    """
    pin = pin if pin is not None else pinned_version()
    skills = resources.list_names("skills")
    results: list[InstallResult] = []

    if SURFACE_PORTABLE in surfaces:
        for name in skills:
            content = compose_skill(name, pin)
            results.append(
                _write_skill_file(
                    target_root / PORTABLE_SKILLS_DIR / name,
                    SURFACE_PORTABLE,
                    name,
                    content,
                )
            )
    if SURFACE_CLAUDE in surfaces:
        for name in skills:
            content = compose_skill(name, pin)
            results.append(
                _write_skill_file(
                    target_root / CLAUDE_SKILLS_DIR / name,
                    SURFACE_CLAUDE,
                    name,
                    content,
                )
            )
    if SURFACE_AGENTS_MD in surfaces:
        block = agents_md_block(pin)
        results.append(_update_agents_md(target_root / "AGENTS.md", block))

    return results


# ─────────────────────────────────────────────────────────────────────────────
# CLI entry point
# ─────────────────────────────────────────────────────────────────────────────


def _print_summary(results: list[InstallResult], pin: str) -> None:
    if not results:
        print("\npprose install: no surfaces selected (nothing to do).")
        return
    print(f"\npprose skill installation (pinned pprose@{pin}):")
    counts: dict[str, int] = {}
    blocked: list[InstallResult] = []
    for r in results:
        counts[r.action] = counts.get(r.action, 0) + 1
        if r.action == "blocked-newer":
            blocked.append(r)
    for action in ("installed", "updated", "unchanged", "blocked-newer"):
        if action in counts:
            print(f"  {action}: {counts[action]}")
    for r in results:
        tag = f"{r.surface}:{r.skill}" if r.skill else r.surface
        marker = "!" if r.action == "blocked-newer" else " "
        print(f"  {marker} [{r.action}] {tag}\t{r.path}")
    if blocked:
        print(
            "\nA newer pprose generated some of those artifacts. Upgrade pprose "
            "(`uv tool install --upgrade pprose` or `uvx pprose@latest --help`) "
            "and re-run install."
        )


_HELP_EPILOG = """\
Scope:
  In a git repo (and not $HOME), --project is implicit.
  Outside a git repo or in $HOME, pass --project or --global explicitly.
  $HOME is always refused in --project mode; use --global for a user-wide install.

Cross-scope coexistence: project-scope skills shadow user-scope skills of the same
name in modern agents (Codex documents this; Claude Code's two discovery paths
imply the same layering). Installing both globally and per-project is a supported
pattern, not a conflict.
"""


def install_main(argv: list[str] | None = None) -> int:
    parser = argparse.ArgumentParser(
        prog="pprose install",
        description=(
            "Install Practical Prose skills into a project (--project, default when "
            "cwd is unambiguously inside a git repo) or globally for the current user "
            "(--global). Outside an unambiguous project context, --project or --global "
            "must be passed explicitly."
        ),
        epilog=_HELP_EPILOG,
        formatter_class=argparse.RawDescriptionHelpFormatter,
    )
    # `--project` and `--global` are mutually exclusive, but we check that manually
    # so the error message uses our own wording (and returns an exit code rather
    # than the SystemExit that add_mutually_exclusive_group raises).
    parser.add_argument(
        "--project",
        action="store_true",
        help="install project-locally (default when cwd is inside a git repo)",
    )
    # `dest='global_'` because `global` is a Python keyword.
    parser.add_argument(
        "--global",
        action="store_true",
        dest="global_",
        help=f"install for the current user ({PORTABLE_SKILLS_DIR} + {CLAUDE_SKILLS_DIR} under $HOME)",
    )
    parser.add_argument(
        "--dir",
        default=None,
        help="project root for --project (default: cwd; incompatible with --global)",
    )
    parser.add_argument(
        "--no-repo-check",
        action="store_true",
        help="allow --project outside a git repo (still refuses $HOME)",
    )
    parser.add_argument(
        "--surfaces",
        default=None,
        metavar="LIST",
        help=(
            "comma-separated subset of surfaces to install. "
            "Values: portable (.agents/skills/), claude (.claude/skills/), "
            "agents-md (AGENTS.md block; project mode only), all (default if omitted). "
            "Example: --surfaces=portable,agents-md"
        ),
    )
    parser.add_argument(
        "--pin",
        metavar="VERSION",
        help=(
            "override the pprose version pin baked into generated skills "
            "(default: installed pprose if it's a real PyPI release, else DISCOVERY_VERSION)"
        ),
    )
    parser.add_argument(
        "--auto",
        action="store_true",
        help="non-interactive (for agents); does not relax the ambiguity check",
    )
    args = parser.parse_args(argv)

    # Parse --surfaces first; argument-shape errors return exit 2 (argparse convention).
    try:
        spec = parse_surfaces(args.surfaces)
    except ValueError as exc:
        print(f"pprose install: error: {exc}", file=sys.stderr)
        return 2

    # Mutually exclusive scope flags.
    if args.project and args.global_:
        print(
            "pprose install: error: --project and --global are mutually exclusive.",
            file=sys.stderr,
        )
        return 2
    if args.global_ and args.dir is not None:
        print(
            "pprose install: error: --global and --dir are mutually exclusive "
            "(--global always writes under $HOME).",
            file=sys.stderr,
        )
        return 2

    # Resolve scope and target.
    if args.global_:
        scope = SCOPE_GLOBAL
        target = Path.home()
    else:
        target = Path(args.dir if args.dir is not None else ".").resolve()
        if args.project:
            scope = SCOPE_PROJECT
        else:
            # Implicit: project iff cwd is unambiguously a project.
            protected = _protected_target_reason(target)
            if protected:
                print(
                    f"pprose install: ambiguous scope ({target} is your "
                    f"{protected}). Pass --project (with --dir <project-root>) or "
                    f"--global explicitly.",
                    file=sys.stderr,
                )
                return 2
            if not _is_within_git_repo(target):
                print(
                    f"pprose install: ambiguous scope ({target} is not inside a "
                    f"git repository). Pass --project --no-repo-check or --global "
                    f"explicitly, or cd into your project root.",
                    file=sys.stderr,
                )
                return 2
            scope = SCOPE_PROJECT

    # Scope-specific guards and surface filtering.
    if scope == SCOPE_PROJECT:
        protected = _protected_target_reason(target)
        if protected:
            print(
                f"pprose install --project: refusing to install into {target} "
                f"({protected}). That would write to your global agent surfaces "
                f"(~/.agents/skills/, ~/.claude/skills/, ~/AGENTS.md). Use "
                f"--global for a user-wide install, or pass --dir <project-root>.",
                file=sys.stderr,
            )
            return 2
        if not args.no_repo_check and not _is_within_git_repo(target):
            print(
                f"pprose install --project: {target} is not inside a git repository. "
                f"Pass --no-repo-check to install here anyway, or cd into your project root.",
                file=sys.stderr,
            )
            return 2
        selected = spec.surfaces
        mode_label = "project mode"
    else:  # SCOPE_GLOBAL
        if spec.agents_md_explicit:
            print(
                "pprose install --global: agents-md is not supported in --global mode "
                "(the global Codex AGENTS.md at ~/.codex/AGENTS.md should stay "
                "user-authored). Drop agents-md from --surfaces, or use --project.",
                file=sys.stderr,
            )
            return 2
        # `--surfaces=all` (or omitted) silently drops agents-md in global mode.
        selected = spec.surfaces - {SURFACE_AGENTS_MD}
        mode_label = "user-global mode"

    pin = args.pin if args.pin else pinned_version()

    # Pre-write target message — last thing printed before any filesystem writes,
    # so an interactive user can ctrl-c if the resolved target or surface list is wrong.
    print(f"Installing pprose skills ({mode_label}) into: {target}")
    if selected:
        print(f"  surfaces: {', '.join(sorted(selected))}")

    results = install(target, selected, pin=pin)
    _print_summary(results, pin)

    blocked = any(r.action == "blocked-newer" for r in results)
    return 1 if blocked else 0


def main(argv: list[str] | None = None) -> int:
    return install_main(argv)


if __name__ == "__main__":
    sys.exit(main())
